<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIMEN" ignored="0" name="Test" tests="10" failures="10" timestamp="22 Feb 2018 22:05:57 GMT" time="318.64" errors="0">
  <testcase name="testCase" time="74.934" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="91.305" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="152.596" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="92.723" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="112.547" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="53.971" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="58.245" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="41.188" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="123.511" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="122.656" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
</testsuite> <!-- Test -->
